name: Build and deploy ASP.Net Core app to Azure Web App - cayers-azure-app-config-dynamic

on:
  push:
    branches:
      - main
    paths:
        - '!**'
        - 'appconfig-sample/**'
        - 'IaC/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
env:
  path: 'appconfig-sample'
  project: 'appconfig-sample.csproj'

jobs:
  build-appconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.path }}
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release ${{ env.project }}
      working-directory: ${{ env.path }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.project }}
      working-directory: ${{ env.path }}
    - name: dotnet publish
      run: dotnet publish -c Release ${{ env.project }} -o ../webapp
      working-directory: ${{ env.path }}
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: webapp
    - uses: actions/upload-artifact@v3
      with:
        name: IaC
        path: IaC        
  deploy-webapp:
    needs: [build-appconfig]
    environment: appConfig
    runs-on: ubuntu-latest
    steps:
     # Checkout code
    - name: Download IaC
      uses: actions/download-artifact@v3
      with:
        name: IaC
        path: iac

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      # Deploy Bicep file
    - name: deploy
      id: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./iac/main.bicep
        parameters: webAppName=${{ secrets.AZURE_APP_NAME }} featureFlagBetaEnabled=true featureFlagFeatureARollout=0
        failOnStdErr: false
   
    - name: Download App
      uses: actions/download-artifact@v3
      with:
        name: app  
        path: app

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ steps.deploy.outputs.webAppName }} # Replace with your app name
        package: 'app'
    
    - name: logout
      run: |
        az logout

  progressive-rollout-webapp:
    needs: [deploy-webapp]
    environment: appConfig
    runs-on: ubuntu-latest
    steps:
     # Checkout code
    - name: Download IaC
      uses: actions/download-artifact@v3
      with:
        name: IaC
        path: iac

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      # Deploy Bicep file
    - name: deploy
      id: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./iac/main.bicep
        parameters: webAppName=${{ secrets.AZURE_APP_NAME }} featureFlagBetaEnabled=true featureFlagFeatureARollout=50
        failOnStdErr: false
   
    - name: logout
      run: |
        az logout

  rollout-webapp:
    needs: [progressive-rollout-webapp]
    environment: appConfig
    runs-on: ubuntu-latest
    steps:
     # Checkout code
    - name: Download IaC
      uses: actions/download-artifact@v3
      with:
        name: IaC
        path: iac

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      # Deploy Bicep file
    - name: deploy
      id: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./iac/main.bicep
        parameters: webAppName=${{ secrets.AZURE_APP_NAME }} featureFlagBetaEnabled=true featureFlagFeatureARollout=100
        failOnStdErr: false
   
    - name: logout
      run: |
        az logout

