name: Build and deploy ASP.Net Core app to Azure Web App - cayers-azure-app-config-quickstart

on:
  push:
    branches:
      - main
    paths:
        - '!**'
        - 'azure-app-config-quickstart/**'
        - 'IaC/**'
env:
  path: 'azure-app-config-quickstart'
  project: 'azure-app-config-quickstart.csproj'

jobs:
  build-quickstart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.path }}
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release ${{ env.project }}
      working-directory: ${{ env.path }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.project }}
      working-directory: ${{ env.path }}
    - name: dotnet publish
      run: dotnet publish -c Release ${{ env.project }} -o ../webapp
      working-directory: ${{ env.path }}
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: webapp
